### ISSUE TITLE
Allow for 4:3 Video embeds

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/webdev-infra#28]
@argyleink has requested a clean way to use the `Video` shortcode to embed with a 4:3 aspect ratio, instead of 16:9.

He's currently resorting to the following hack:

```
  <style style="display: none">
    .adjusted-aspect-ratio {
      aspect-ratio: 4/3;
    }
  </style>
  {% Video
    src="video/vS06HQ1YTsbMKSFTIPl2iogUQP73/rx8k6w5iQnEOwqOoUNNG.mp4",
    autoplay="true",
    loop="true",
    muted="true",
    class="adjusted-aspect-ratio"
  %}
```

**Comment by argyleink** [comment]
a shortcode option seems right, something like?

```
  {% Video
    src="video/robo-vomit.mp4",
    autoplay="true",
    loop="true",
    muted="true",
    ratio="4/3"
  %}
```

**Comment by jeffposnick** [comment]
It's worth noting that the style for the `<video>` on web.dev comes from [here](https://github.com/GoogleChrome/web.dev/blob/696a415223d172f81dd33fd48e4fd1fb8c5412de/src/scss/next.scss#L699-L704):

```
/// Video related elements
video,
.youtube {
  position: relative;
  aspect-ratio: 16/9;
}
```

Maybe what would ultimately make sense is to keep the `Video` shortcode as-is, and just add

```
.ratio43 {
  aspect-ratio: 4/3;
}
```

as a class that anyone could use via `class="ratio43"`, formalizing what @argyleink is already doing?

What's your opinion, @devnook? I'm not as familiar with the way our component/styling system is supposed to work.

**Comment by jakearchibald** [comment]
Proposal: change https://github.com/GoogleChrome/webdev-infra/blob/main/shortcodes/Video.js so if both "width" and "height" are provided, it generates an inline style of `style="aspect-ratio: ${width} / ${height}"`.

**Comment by jeffposnick** [comment]
That seems reasonable to me!

**Comment by jakearchibald** [comment]
It might be safer to do `style="--vid-width: ${width}; --vid-height: ${height}"`, then have a style rule like:

```css
video {
  width: 100%;
  height: auto;
  aspect-ratio: var(--vid-width) / var(--vid-height);
}
```

Then it has lower specificity than an inline style.

**Comment by jakearchibald** [comment]
- https://github.com/GoogleChrome/webdev-infra/pull/32
- https://github.com/GoogleChrome/web.dev/pull/8399
- https://github.com/GoogleChrome/developer.chrome.com/pull/3295

**Comment by tunetheweb** [comment]
OK so this is what I think it needs, added to next.scss

Add `--var-width`, `--var-height`, and `aspect-ratio`:

```css
/// Video related elements
video,
.youtube {
  --var-width: 16;
  --var-height: 9;
  position: relative;
  aspect-ratio: var(--vid-width) / var(--vid-height);
}
```

Add `height: auto` to `video` further down (probably this should just be merged with above)?

```css
/// Media
video {
  max-width: 100%;
  height: auto;
}
```

**Comment by jakearchibald** [comment]
I'm wary of changing things for existing content

**Comment by tunetheweb** [comment]
Not sure what you mean?

The current CSS for web.dev has 16/9:

https://github.com/GoogleChrome/web.dev/blob/076e60738ad7c89c2f733db48c7c7c7221100784/src/scss/next.scss#L699

```css
/// Video related elements
video,
.youtube {
  position: relative;
  aspect-ratio: 16/9;
}
```

So if you're planning on changing that to `aspect-ratio: var(--vid-width) / var(--vid-height);` then you will break that for any existing content, that is not currently supplying a width and height (basically all of them right now). And if you don't add that, then you've not solved this. So I think you need to do the first change I suggested (`/// Video related elements` changes above) don't you?

Also because that same stylesheet has this:

```css
/// Media
video {
  max-width: 100%;
}
```

As soon as you start adding width and height (to allow the 4:3 aspect ratio to be set), then you will have a `height` that is not caped, and a `width` that is capped at 100%. So I think you need to do that second change I suggested, if you want to be able to give an explicit height and width to allow automatic setting of `aspect-ratio`. And if you don't add that, then you've not solved this. 

So I don't think this proposal will work without both of those, or you will break existing content.

On the plus side, I think these are safe changes from some quick tests.

Does that make sense?
